/* Generated By:JavaCC: Do not edit this line. MATDSLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MATDSLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int MULTIPLY = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int TRANSPOSE = 8;
  /** RegularExpression Id. */
  int INVERSE = 9;
  /** RegularExpression Id. */
  int ADJOINT = 10;
  /** RegularExpression Id. */
  int INTEGER = 11;
  /** RegularExpression Id. */
  int LF = 12;
  /** RegularExpression Id. */
  int DOT = 13;
  /** RegularExpression Id. */
  int SEMICOLON = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int OPEN_CBRACKET = 16;
  /** RegularExpression Id. */
  int CLOSE_CBRACKET = 17;
  /** RegularExpression Id. */
  int OPEN_SBRACKET = 18;
  /** RegularExpression Id. */
  int CLOSE_SBRACKET = 19;
  /** RegularExpression Id. */
  int REAL = 20;
  /** RegularExpression Id. */
  int SYMBOL = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\'\"",
    "\"-1\"",
    "\"$\"",
    "<INTEGER>",
    "\"\\n\"",
    "\".\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<REAL>",
    "<SYMBOL>",
  };

}
